name: 'Trufflehog Actions Scan'
description: 'Scan repository for secrets with basic trufflehog defaults in place for easy setup.'
author: 'Ed Plato'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.DEFAULT_BRANCH }}
inputs:
  DEFAULT_BRANCH:
    description: "master or main"
    required: false
branding:
  icon: 'shield'  
  color: 'yellow'
