name: 'Trufflehog Actions Scan'
description: 'Scan repository for secrets with basic trufflehog defaults in place for easy setup.'
author: 'Ed Plato'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.DEFAULT_BRANCH }}
inputs:
  DEFAULT_BRANCH:
    description: "master or main"
    required: false
  githubToken:
    description: 'GitHub Token to access a private repository.'
    required: false
  scanArguments:
    description: 'Argument options for scan.'
    required: false
outputs:
  check_secrets_warning:
    description: 'Check secrets warning output'
branding:
  icon: 'shield'  
  color: 'yellow'
