name: Check Secrets
on: push
jobs:
  check-secrets:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Scanning with Trufflehog
        id: check-secrets
        uses: ./
        with:
          DEFAULT_BRANCH: main
      - name: Comment high entropy
        uses: actions/github-script@0.9.0
        env:
          HIGH_ENTROPY_OUTPUT: ${{ steps.check-secrets.outputs.high_entropy }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const high_entropy=$(echo "$HIGH_ENTROPY_OUTPUT" | jq)
          const output = `#### WARNING: HIGH ENTROPY\`
          
          <details><summary>More...</summary>
          
          \`\`\`\n
          $high_entropy
          \`\`\`

          <details>

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
