name: Check Secrets
on: push
jobs:
  check-secrets:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Scanning with Trufflehog
        id: check-secrets
        uses: ./
        with:
          DEFAULT_BRANCH: main
      - name: Comment high entropy
        env:
          HIGH_ENTROPY_OUTPUT: ${{ steps.check-secrets.outputs.high_entropy }}
        run: |
          echo "$HIGH_ENTROPY_OUTPUT" | jq

